{
    "event_type": "compute.exception",
    "payload": {
        "nova_object.data": {
            "exception": "AggregateNameExists",
            "exception_message": "Aggregate versioned_exc_aggregate already exists.",
            "function_name": "_aggregate_create_in_db",
            "module_name": "nova.objects.aggregate",
            "traceback": "Traceback (most recent call last):\n  File \"nova/compute/manager.py\", line ..."
        },
        "nova_object.name": "ExceptionPayload",
        "nova_object.namespace": "nova",
        "nova_object.version": "1.1"
    },
    "priority": "ERROR",
    "publisher_id": "nova-api:fake-mini"
}
